---
# tasks file for ssh-harden
- name: Disable root login in the ssh config
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#?(PermitRootLogin)\s.*$'
    replace: '\1 no'
    validate: "sshd -t -f %s"
- name: Disable password authentication
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#?(PasswordAuthentication)\s.*$'
    replace: '\1 no'
    validate: "sshd -t -f %s"
- name: Reload service httpd, in all cases
  service:
    name: ssh
    state: reloaded
- name: Install modprobe for iptables filter
  apt:
    name: kmod
    state: present
- name: Install iptables
  apt:
    name: iptables
    state: present
- name: Preserve ESTABLISHED connections and don't drop ansible
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow established connections
- name: Allow new incoming SYN packets on TCP port 22 (SSH).
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new SSH connections.
- name: Set the policy for the INPUT chain to DROP
  iptables: 
    chain: INPUT
    policy: DROP


  
