- hosts: sshservers
  become: yes
  become_user: root
  tasks:
    - name: Install sshd
      apt:
        name: openssh-server
        state: present

  roles:
    - motd-setup
    - name: ssh-harden
      become: yes
    - motd-test
