- hosts: sshservers
  become: yes
  become_user: root
  tasks:
    - name: Install sshd
      apt:
        name: openssh-server
        state: present
  roles:
    - motd-setup
    - ssh-harden
      # - motd-test
